####USER CMS APIS


### root API
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"Niraj",
    "lname": "Bohora",
    "email":"jasss@gmil.com",
    "phone":"041000000",
    "password":"12345667",
    "address":"sydney, NSW",
    "gender":"male"
    

}

### verify user email
PATCH http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
"pin":"451442",
"email":"jasss@gmil.com"
}