####USER CMS APIS


### root API
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"Niraj",
    "lname": "Bohora",
    "email":"jsa@gmil.com",
    "phone":"041000000",
    "password":"12345667",
    "address":"sydney, NSW",
    "gender":"male"
    

}

### verify user email

PATCH http://localhost:3000/email-verifiation?
Content-Type: application/json

{
"pin":"835412",
"email": "jsa@gmil.com"
}