####USER CMS APIS


### root API
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"Niraj",
    "lname": "Bohora",
    "email":"1q3@gmil.com",
    "phone":"041000000",
    "password":"12345667",
    "address":"sydney, NSW",
    "gender":"male"
    

}

### verify user email
PATCH http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
"pin":"672667",
"email":"13@gmil.com"
}


### login user
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email":"qaq@gmail.com",
    "password":"12345678"
}
 
### get new acccess token router
GET http://localhost:8000/api/v1/token/
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InFhcUBnbWFpbC5jb20iLCJpYXQiOjE2MzY2ODQ2NjksImV4cCI6MTYzOTI3NjY2OX0.PnBPGGIOk567O6AWFyR-3hzyebKmwu5JIVanodgiGEI